create table users (
    user_id number(19) generated by default as identity primary key,
    username varchar2(100) not null,
    password_hash varchar2(255) not null,
    role varchar2(30) not null,
    created_at timestamp default systimestamp not null,
    constraint uk_users_username unique (username),
    constraint ck_users_role check (role in ('ADMIN', 'QA_USER'))
);

create table environments (
    env_id number(19) generated by default as identity primary key,
    name varchar2(100) not null,
    description varchar2(500),
    db_type varchar2(30) not null,
    jdbc_url varchar2(1000) not null,
    db_username varchar2(200) not null,
    db_password_enc clob not null,
    created_at timestamp default systimestamp not null,
    constraint uk_environments_name unique (name)
);

create table sql_definitions (
    sql_id number(19) generated by default as identity primary key,
    sql_name varchar2(200) not null,
    sql_description varchar2(1000),
    sql_text clob not null,
    created_at timestamp default systimestamp not null,
    constraint uk_sql_definitions_name unique (sql_name)
);

create table user_allowed_sql (
    user_id number(19) not null references users(user_id) on delete cascade,
    sql_id number(19) not null references sql_definitions(sql_id) on delete cascade,
    created_at timestamp default systimestamp not null,
    primary key (user_id, sql_id)
);

create table user_allowed_env (
    user_id number(19) not null references users(user_id) on delete cascade,
    env_id number(19) not null references environments(env_id) on delete cascade,
    created_at timestamp default systimestamp not null,
    primary key (user_id, env_id)
);

create table execution_history (
    execution_id number(19) generated by default as identity primary key,
    user_id number(19) not null references users(user_id),
    env_id number(19) not null references environments(env_id),
    sql_id number(19) not null references sql_definitions(sql_id),
    started_at timestamp default systimestamp not null,
    status varchar2(30) not null,
    records_returned number(10),
    rows_affected number(10),
    error_message varchar2(2000),
    client_ip varchar2(100),
    constraint ck_execution_history_status check (status in ('SUCCESS', 'FAILED'))
);

create index idx_user_allowed_sql_user on user_allowed_sql(user_id);
create index idx_user_allowed_sql_sql on user_allowed_sql(sql_id);
create index idx_user_allowed_env_user on user_allowed_env(user_id);
create index idx_user_allowed_env_env on user_allowed_env(env_id);
create index idx_execution_history_user on execution_history(user_id);
create index idx_execution_history_env on execution_history(env_id);
create index idx_execution_history_sql on execution_history(sql_id);
create index idx_execution_history_started on execution_history(started_at);
